################################################################################################
# Requirements & Config.
################################################################################################

#-----------------------------------------------
# Build Settings
#-----------------------------------------------
markdown: kramdown
permalink: pretty
exclude: ['README.md', 'LICENSE.txt', 'CNAME']

#-----------------------------------------------
# Plugins
#-----------------------------------------------
plugins_dir:
- jekyll-sitemap
#- jekyll-menus

safe: false

################################################################################################
# Site Settings
################################################################################################
title: "BSidesNYC"
email: "bsides@bsidesnyc.org"
twitterAccount: "@bsidesnyc"
description: "BSides NYC is an Information / Security conference that’s different. We’re a 100% volunteer organized event put on by and for the community, and we truly strive to keep information free."
url: "https://bsidesnyc.org" #https://bsidesnyc.github.io
timezone: "America/New_York"
conYear: "2023"
previousSponsorCount: "22"
previousAttendeeCount: "600"
logoImage: "/about/logo_white.png"
#logoImageHead: "/about/logo_black.png"

#-----------------------------------------------
# Footer
#-----------------------------------------------
socialLinks:
 - {link: "https://twitter.com/bsidesnyc", icon: "twitter"}
 - {link: "https://www.linkedin.com/company/bsidesnyc", icon: "linkedin"}
footerBlocks:
 -
  title: "Links"
  links:
   - {permalink: "/", text: "BSidesNYC"}
   - {link: "http://www.securitybsides.com", text: "Security BSides"}
 -
  title: "Contacts"
  links:
   - {permalink: "/contact/", text: "Contact Us"}
   - {link: "https://join.slack.com/t/bsidesnyc/shared_invite/zt-1lbapliq9-Sym1TaYpxh3zmfalcdYHjw", text: "Join our Slack"}
   - {link: "mailto:bsides@bsidesnyc.org", text: "bsides(at)bsidesnyc.org"}
 -
  title: "Policies"
  links:
   - {permalink: "/policies/", text: "CoC & Anti-Harassment"}
 -
  title: "Press"
  links:
   - {permalink: "/press-pass/", text: "Press Passes"}

#-----------------------------------------------
# Head
#-----------------------------------------------
metaKeywords: "bsides, security, bsidesnyc, conference, nyc"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

#-----------------------------------------------
# Navigation
#-----------------------------------------------
navigationLinks:
 - {permalink: "/about/", text: "About"}
 - {permalink: "/sponsors/", text: "Sponsors"}
 - {permalink: "/volunteers/", text: "Volunteer"}
 - {permalink: "/cfp/", text: "CFP"}
bottomNavigationLinks:
 - {permalink: "/cfp/", text: "Become a speaker"}
rightNavigationButtons:
 - {permalink: "/volunteers/", text: "Volunteer!"}

################################################################################################
# Block Data
################################################################################################

#-----------------------------------------------
# About
#-----------------------------------------------
aboutTitle: "What is BSidesNYC?"
aboutBlock:
 - {title: "Conference", image: "logo_black.png", text: "BSidesNYC is an Information / Security conference that’s different. We’re a 100% volunteer organized event put on by and for the community and we truly strive to keep information free." }
 - {title: "Villages", image: "toool.png", text: "Rather pick some locks or get hands on with some hardware hacking? We got ya covered." }

#-----------------------------------------------
# CFP Block
#-----------------------------------------------
cfpTitle: "Call For Papers"
cfpBoardTitle: "CFP Board"
cfpUrl: "https://docs.google.com/forms/d/e/1FAIpQLSes8dIfojKqXatyC6lNug41d_jsnio0LdIZRlFWms9sbWiUxw/viewform?usp=sf_link"
cfpOpenDate: "November 08, 2022"
cfpCloseDate: "February 06, 2023"
cfpAcceptanceDate: "March 08, 2023"
cfpDuration: "CFP submissions will be accepted from"
cfpAcceptance: "Speaker acceptance notices will start being sent out on"
cfpProcessReviewText: ["Our current conference timeline allocates ~3 months for our CFP to be open for submissions. While there is a little flexibility for late submissions, we generally <b>will not accept submissions after our CFP has been closed for 24+ hrs.</b>",

"After our CFP has been closed, our CFP review board has ~1 month to look over and score all submissions.",

"Based on the ratings from our CFP review board, the submissions with the highest score are put into our first round of acceptance notices.",

"We allow ~1 week for these submitters to respond. <i>If we can not get a hold of, or hear back from, said submitter(s) then we move down our acceptance list</i>. Additionally, circumstatnces may arrise which prevent a submitter from being able or willing to present at our conference. If this occurs, we must once again continue down the acceptance list.",

"This is usually resolved within a week or two, but as you can imagine, we can not send out rejection notices until we have enough talks to fill our schedule.", "Once we have enough acceptances, we will send out notices to those who did not make the final cut. Depending on the volume of CFP submissions, we may not be able to provide personal feedback for each CFP submission."]
cfpProcessAcceptedText: ["Ideally, we will be able to give you 1+ month of acceptance notice so you can schedule any necessary travel arrangements. <b>If your attendance requires any visa paperwork, please let us know ahead of time</b>.",

"We typically do not have a speaker party the day before the conference; However, speakers have set up their own dinners for those in town in previous years.",

"~7-10 days after you receive your acceptance notice, you will be contacted to ask if you would like to have your bio and/or headshot published on our site. If so, please provide us with this information at this time.",

"Additionally, we will be posting the speaker list and talk abstracts so please let us know if anything has changed (title, abstract etc.) A.S.A.P.",

"As always, if you would like to have someone come to the conference with you, please just send us their information so we can register them."]

#-----------------------------------------------
# Contact
#-----------------------------------------------
contactTitle: "Need to get in touch?"
contactTextTwitter: "Follow us on Twitter"
contactTextEmail: "or email us at"
contactMailingListText: "Just looking to stay in the loop? Use the form below to get announcements on all things BSidesNYC or join our <a href=\"https://join.slack.com/t/bsidesnyc/shared_invite/zt-1lbapliq9-Sym1TaYpxh3zmfalcdYHjw\" target=\"_blank\">Slack</a> workspace."
contactVolunteersMailingListText: "Looking to sign up as a volunteer? Head over to our <a href=\"/volunteers/\">volunteers page</a> and sign-up."

#-----------------------------------------------
# Event Intro
#-----------------------------------------------
eventImage: "nyc_skyline.jpg"
eventTitle: "BSidesNYC"
eventDate: "April 22, 2023"
eventInfo: "The next BSidesNYC will take place in April 22, 2023.  To stay updated on volunteer opportunities, and other news, follow us on Twitter <a href=\"https://twitter.com/bsidesnyc\" target=\"_blank\">@BSidesNYC</a> and sign up for the mailing list."
eventButtons:
 - {permalink: "/sponsors/", text: "Become a sponsor", id: "sponsors"}

#-----------------------------------------------
# Location Block
#-----------------------------------------------
locationBlockTitle: "Location"
eventLocationName: "Digital Forensics and Cybersecurity Program @ John Jay College of Criminal Justice"
eventStreetAddress: "524 W 59th St."
eventAddressLocality: "New York"
eventAddressLocalityRegion: "NY"
eventPostalCode: "10019"
eventAddressCountry: "USA"
eventNavigationLink: https://goo.gl/maps/7vwHt4ARqjr
eventStartTime: "2018-01-20T08:00"
eventDoorTime: "09:00"
eventEndTime: "2018-01-20T17:00"
eventPlaceCoordinates: "40.7709863, -73.9899653"
mapCenterCoordinates: "40.7709863, -73.9899653"
mapMobileCenterCoordinates: "40.7709863, -73.9899653"

#-----------------------------------------------
# Sponsors
#-----------------------------------------------
sponsorsTitle: "Sponsors"
sponsorsUrl: "/sponsors/"
sponsorsButton: "Become a sponsor"

#-----------------------------------------------
# Sponsorship
#-----------------------------------------------
sponsorshipTitle: "Sponsorship"
sponsorshipButton: "Download our Sponsorship Kit (PDF)"
sponsorshipKitUrl: "/assets/BSidesNYC-2023-Sponsorship-Kit.pdf"

#-----------------------------------------------
# Subscribe
#-----------------------------------------------
subscribeImage: #"subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeInfo: "We'll only use your email for BSidesNYC announcements. We respect privacy, and don't provide anyone (including sponsors) with this type of information."

#-----------------------------------------------
# Registration | Tickets
#-----------------------------------------------
# flip this to make a quick change whether we have tickets open or closed
ticketsOpen: false
ticketsOpenDate: "December 13, 2017 10:00:00"
ticketsText: "Unable to expense other, costly conferences?

No worries, at BSidesNYC we strive to make the cost of attendance free."
ticketsUpdateText: "Aw snap - looks like all of our tickets were snatched up! Stay tuned for updates on additional opportunities to grab one."
ticketsNextReleaseDate: "January 9th, 2018 10:00:00"
ticketsNextReleaseText: "Didn't get a ticket during our first round? No need to pout - revisit this page for our next round of tickets on "
# add EventBrite URL to `link` when `ticketsOpen` is set to `true`
ticketsButtons:
 - {link: "https://bsidesnyc.eventbrite.com", text: "Get Tickets!", id: "tickets_button_external"}

#-----------------------------------------------
# Venue
#-----------------------------------------------
venueBlockTitle: "Venue"
venueImageAtrium: "atrium.jpg"
venueRoomImage1: "240.jpg"
venueRoomImage2: "L615.jpg"
venueRoomImage3: "L763.jpg"
venueTitle: "John Jay College of Criminal Justice"
venueFeatures: ["Guest Wi-Fi will be available." ]
venueRooms:
  - {id: "0", name: "Lynn & Jules Kroll Atrium", image: "atrium.jpg", link: "http://www.locationsnewyorkcity.com/mainlocation/lynn-jules-kroll-atrium/"}

#-----------------------------------------------
# Volunteers
#-----------------------------------------------
volunteersTitle: "Want to be involved?"
volunteersText: "We are looking for individuals to help in a variety of areas – are you interested in lending a hand? If so, use the form below to sign-up and we'll reach out to you when the conference nears.


Over email? Join our <a href=\"https://join.slack.com/t/bsidesnyc/shared_invite/zt-1lbapliq9-Sym1TaYpxh3zmfalcdYHjw\" target=\"_blank\">Slack</a> workspace instead."
volunteersSubscribeTitle: "Join the Team"
