################################################################################################
# Requirements & Config.
################################################################################################

#-----------------------------------------------
# Build Settings
#-----------------------------------------------
markdown: kramdown
permalink: pretty
exclude: ['README.md', 'LICENSE.txt', 'CNAME']

#-----------------------------------------------
# Plugins
#-----------------------------------------------
plugins_dir:
- jekyll-sitemap
#- jekyll-menus

safe: false

################################################################################################
# Site Settings
################################################################################################
title: "BSidesNYC"
email: "bsides@bsidesnyc.org"
twitterAccount: "@bsidesnyc"
description: "BSides NYC is an Information / Security conference that’s different. We’re a 100% volunteer organized event put on by and for the community, and we truly strive to keep information free."
url: "https://bsidesnyc.org" #https://bsidesnyc.github.io
timezone: "America/New_York"
conYear: "2024"
previousSponsorCount: "22"
previousAttendeeCount: "800"
logoImage: "/about/logo_white.png"
#logoImageHead: "/about/logo_black.png"
checkinMessage: "General attendee check-in opens at 8:30am ET. Speakers, sponsors, villages, CTF organizers are welcome to come early at 8:00am ET to give extra time for set up."
contactUs: "/about/#contact-us"

# 
# Slack Invite URL
# Also change this in the links section below
#
slackInviteUrl: https://join.slack.com/t/bsidesnyc/shared_invite/zt-2s0qky0jo-sfcQ7SwHUlFMq4_wQNYYKQ

#-----------------------------------------------
# Footer
#-----------------------------------------------
socialLinks:
  - icon: twitter
    link: https://twitter.com/bsidesnyc
  - icon: linkedin
    link: https://www.linkedin.com/company/bsidesnyc

footerBlocks:
  - title: Links
    links:
      - text: BSidesNYC
        permalink: /
      - text: Security BSides
        link: http://www.securitybsides.com
  - title: Contacts
    links:
      - text: Mailing List
        permalink: /about/#contact-us
      - text: Join our Slack
        link: https://join.slack.com/t/bsidesnyc/shared_invite/zt-2s0qky0jo-sfcQ7SwHUlFMq4_wQNYYKQ
      - text: "bsides(at)bsidesnyc.org"
        link: mailto:bsides@bsidesnyc.org
      - text: Volunteer
        permalink: /about/#volunteers
  - title: Policies
    links:
      - text: "CoC & Anti-Harassment"
        permalink: /policies/
  - title: Press
    links:
      - text: Press Passes
        permalink: /about/#contact-us

#-----------------------------------------------
# Head
#-----------------------------------------------
metaKeywords: "bsides, security, bsidesnyc, conference, nyc"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

#-----------------------------------------------
# Navigation
#-----------------------------------------------
navigationLinks:
 - {permalink: "/venue/", text: "Venue"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/villages/", text: "Villages"}
 - {permalink: "/ctf/", text: "CTF"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/registration/", text: "Registration"}
 - {permalink: "/sponsors/", text: "Sponsors"}
 - {permalink: "/cfp/", text: "CFP"}
 - {permalink: "/about/", text: "About"}
bottomNavigationLinks:
rightNavigationButtons:

################################################################################################
# Block Data
################################################################################################

#-----------------------------------------------
# About
#-----------------------------------------------
aboutTitle: "About BSidesNYC"
aboutCaption: "BSidesNYC is an Information / Security conference that’s different. We’re a 100% volunteer organized event put on by and for the community and we truly strive to keep information free."
aboutBlock:
  - {title: "Conference", image: "conference.jpg", text: "Three technical tracks based on the themes of Red Teams, Blue Teams, and Other content. Plus an Entreprenuer track for the bold!" }
  - {title: "Villages", image: "villages.jpg", text: "Learn how to lockpick, solder, and about local community-driven organizations." }
  - {title: "Capture The Flag", image: "ctf.jpg", text: "Multiple CTFs with varying levels of technical depth." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "700", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "45", specialCharacter: "+", info: "hours", detail: "of security content"}
 - {count: "58", specialCharacter: "+", info: "speakers", detail: "from across the world"}
 - {count: "5", specialCharacter: "", info: "parallel tracks", detail: "plus villages"}

#-----------------------------------------------
# CFP Block
#-----------------------------------------------
cfpTitle: "Call For Papers"
cfpBoardTitle: "CFP Board"
cfpUrl: "https://docs.google.com/forms/d/e/1FAIpQLSes8dIfojKqXatyC6lNug41d_jsnio0LdIZRlFWms9sbWiUxw/viewform?usp=sf_link"
cfpOpenDate: "April 16, 2024"
cfpCloseDate: "July 19, 2024"
cfpAcceptanceDate: "July 19, 2024"
cfpDuration: "CFP submissions will be accepted from"
cfpAcceptance: "Speaker acceptance notices will start being sent out on"
cfpProcessReviewText: ["Our current conference timeline allocates ~3 months for our CFP to be open for submissions.",

"After our CFP has been closed on July 19, 2024, our CFP review board has ~1 week to look over and score all submissions.",

"Based on the ratings from our CFP review board, the submissions with the highest score are put into our first round of acceptance notices, which start on July 26, 2024.",

"We allow ~1 week for these submitters to respond. <i>If we can not get a hold of, or hear back from, said submitter(s) then we move down our acceptance list</i>. Additionally, circumstatnces may arrise which prevent a submitter from being able or willing to present at our conference. If this occurs, we must once again continue down the acceptance list.",

"This is usually resolved within a week or two, but as you can imagine, we can not send out rejection notices until we have enough talks to fill our schedule.", "Once we have enough acceptances, we will send out notices to those who did not make the final cut, probably starting August 9, 2024. Depending on the volume of CFP submissions, we may not be able to provide personal feedback for each CFP submission."]
cfpProcessAcceptedText: ["Acceptance notice go out over a month ahead of the conference so you can schedule any necessary travel arrangements. <b>If your attendance requires any visa paperwork, please let us know ahead of time</b>.",

"Additionally, we will be posting the speaker list and talk abstracts so please let us know if anything has changed (title, abstract etc.) A.S.A.P.",

"As always, if you would like to have someone come to the conference with you, please just send us their information so we can register them."]

#-----------------------------------------------
# Villages
#-----------------------------------------------
villagesAboutTitle: "About Villages"
villagesTitle: "BSidesNYC 2023 Villages"
villagesUrl: "/villages/"
villages:
  - title: "NYC Resistor"
    url: "https://www.nycresistor.com"
    logo: "nycresistor.png"
    handson: true
    description: "We Learn, Share, and Make things. NYC Resistor is a hacker collective with a shared space located in Boerum Hill, Brooklyn. We meet regularly to share knowledge, hack on projects together, and build community."
  - title: "Industrial Control System (ICS) Village"
    url: "https://www.icsvillage.com/"
    logo: "ics.png"
    handson: true
    description: "We bring you real components such as programmable logic controllers (PLC), human-machine interfaces (HMI), remote telemetry units (RTU), and actuators to simulate a realistic environment by using commonly used components throughout different industrial sectors. You will be able to connect your machine to the different industrial components and networks and try to assess these ICS devices with common security scanners to sniff the industrial traffic, and more!"
  - title: "Aerospace Village"
    url: "https://www.aerospacevillage.org/"
    logo: "aerospace.svg"
    handson: true
    description: "The Aerospace Village is a diverse community of hackers, engineers, pilots, policy leaders and more from across both the public and private sectors. We believe the flying public deserves safe, reliable, and trustworthy air travel, which is highly dependent on secure aviation and space operations."
  - title: "Blacks In Cybersecurity™"
    url: "https://www.blacksincyberconf.com/"
    logo: "bic.png"
    handson: false 
    description: "Blacks In Cybersecurity™ is a meetup group and conference series to help highlight and elevate the Black community in Cybersecurity. The official mission of Blacks In Cybersecurity™ (BIC) is to encourage the participation of the Black community in Cybersecurity."
  - title: "Women's Society of Cyberjutsu"
    url: "https://womenscyberjutsu.org/"
    logo: "cyberjutsu.png"
    handson: false
    description: "Women’s Society of Cyberjutsu (WSC) is a National 501(c)3 non-profit community, focused on empowering women to succeed in the cybersecurity industry. WSC’s mission is to advance women in cybersecurity careers by providing programs and partnerships that promote hands-on training, networking, education, mentoring, resource-sharing and other professional opportunities."
  - title: "The Diana Initiative"
    url: "https://www.dianainitiative.org/"
    logo: "diana.jpg"
    handson: false
    description: "The Diana Initiative is a diversity-driven conference committed to helping all underrepresented people in Information Security. The Diana Initiative features multiple speaker tracks, capture-the-flag competitions, villages with hands-on activities, and workshops."
  - title: "Raíces Cyber"
    url: "https://www.raicescyber.org/newyorkcity-chapter"
    logo: "raices.png"
    handson: false
    description: "Raíces Cyber's Mission is to Encourage and Support the Hispanic and Latino Cyber and Technology Community to Achieve Greater Representation in the World. We are doing that with our four main pillars. Continued Support and Encouragement to and from the Community, Education for all career levels, Access to valuable resources, Constructive Networking and the forming of STRONG bonds (“Roots”). "

#-----------------------------------------------
# Event Intro
#-----------------------------------------------
eventImage: "nyc_skyline.jpg"
eventTitle: "BSidesNYC"
eventDate: "19 October 2024"
eventInfo: "The next BSidesNYC will take place in 19 October 2024. To stay updated on volunteer opportunities, and other news, follow us on Twitter <a href=\"https://twitter.com/bsidesnyc\" target=\"_blank\">@BSidesNYC</a> and sign up for the mailing list."
eventButtons:
 - {permalink: "/sponsors/", text: "Become a sponsor", id: "sponsors"}

#-----------------------------------------------
# Location Block
#-----------------------------------------------
locationBlockTitle: "Location"
eventLocationName: "Digital Forensics and Cybersecurity Program @ John Jay College of Criminal Justice"
eventStreetAddress: "524 W 59th St."
eventAddressLocality: "New York"
eventAddressLocalityRegion: "NY"
eventPostalCode: "10019"
eventAddressCountry: "USA"
eventNavigationLink: https://goo.gl/maps/7vwHt4ARqjr
eventStartTime: "2024-10-19T08:00"
eventDoorTime: "09:00"
eventEndTime: "2024-10-19T17:00"
eventPlaceCoordinates: "40.7709863, -73.9899653"
mapCenterCoordinates: "40.7709863, -73.9899653"
mapMobileCenterCoordinates: "40.7709863, -73.9899653"

#-----------------------------------------------
# Logistics | Directions
#-----------------------------------------------
directionsTitle: #"Find your way here"
directionsDistance: "Distance"
directionsDriving: "DRIVING"
directionsWalking: "WALKING"
directionsBicycling: "BICYCLING"
directionsTransit: "TRANSIT"
directionsFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "40.7709863, -73.9899653"
logisticsMapMobileCenterCoordinates: "40.7709863, -73.9899653"
logisticsMapAutoDirections: false

# Logistics Direction Details
directionDetailsImage: "columbus_circle.jpg"
directionDetailsTitle: "Getting Here"
directionDetailsCards:
 - {title: "Airports", information: 'The conference is easily accessible from the <b>JFK</b>, <b>LGA</b>, or <b>EWR</b> airports via public transportation (subway, bus, taxi) or ride-sharing services (uber, lyft etc.)'}
 - {title: "Public Transit", information: "The closest subway station is <b>59 St. - Columbus Circle</b> (A,B,C & D lines). From this stop, it is less than a .5 mile walk."}
 - {title: "Hotels", information: "<a href='https://www.marriott.com/en-us/hotels/nycft-fairfield-inn-and-suites-new-york-manhattan-central-park/overview/'>Fairfield Inn & Suites New York Manhattan/Central Park</a> is right next door."}

#-----------------------------------------------
# Partners
#-----------------------------------------------
partnersTitle: "Partners"

#-----------------------------------------------
# Sponsors
#-----------------------------------------------
sponsorsTitle: "Our Sponsors"
sponsorsUrl: "/sponsors/"
sponsorsButton: "Become a sponsor"

#-----------------------------------------------
# Sponsorship

sponsorshipTitle: "Want to sponsor?"
sponsorshipButton: "Download Prospectus"
sponsorshipKitUrl: "/assets/BSidesNYC-2024-Sponsorship-Prospectus.pdf"

#-----------------------------------------------
# Subscribe
#-----------------------------------------------
subscribeTitle: "Subscribe for updates"
subscribeInfo: "^^^ Please ignore this message above from our mailing list provider. We use the free edition, so this get embedded.<p>We'll only use your email for BSidesNYC announcements. We respect privacy, and don't provide anyone (including sponsors) with this type of information."

#-----------------------------------------------
# Registration | Tickets
#-----------------------------------------------
# flip this to make a quick change whether we have tickets open or closed
ticketsOpen: false
ticketsOpenDate: "September 15, 2024 20:00:00"
ticketsText: "Unable to expense other, costly conferences?

No worries, at BSidesNYC we strive to make the cost of attendance minimal."
ticketsUpdateText: "Aw snap - looks like all of our tickets were snatched up! Stay tuned for updates on additional opportunities to grab one."
#ticketsNextReleaseDate: "January 9th, 2018 10:00:00"
#ticketsNextReleaseText: "Didn't get a ticket during our first round? No need to pout - revisit this page for our next round of tickets on "
# add EventBrite URL to `link` when `ticketsOpen` is set to `true`
ticketsButtons:
 - 
priceInfo: "Tickets are sold out. We will release a small batch of additional free tickets on October 14. We don’t know yet how many tickets will be in that batch. It depends on how many of the reserved tickets will get used."

#-----------------------------------------------
# Venue
#-----------------------------------------------
venueTitle: John Jay College of Criminal Justice
venueAddress: 524 W. 59th Street, New York, NY
venuePhotosPrimary: atrium.jpg
venuePhotosSecondary:
  - 240.jpg
  - L615.jpg
  - L763.jpg
venueMapsIntro: "Tracks are split across multiple floors. You'll enter and register on the Ground floor where the Red Track (L.63), Keynote (L.63), and Entrepreneur Track (L.61) are. Go down via stairs or elevator to Lower Level (L2) for the Blue Track (L2.84) and Other Track (L2.85). Go up via elevator to the 6th Floor for the Villages (Moot Court) and to the 9th for CTF."
venueFloorMaps:
  - name: Ground Floor (L)
    image: bsidesnyc-johnjay-ground-floor.png
  - name: Lower Level (L2)
    image: bsidesnyc-johnjay-L2.png
  - name: 6th Floor
    image: bsidesnyc-johnjay-6th.png
  - name: 9th Floor
    image: bsidesnyc-johnjay-9th.png

#-----------------------------------------------
# Volunteers
#-----------------------------------------------
volunteersTitle: "Want to Volunteer?"
volunteersSubscribeTitle: "Join the Team"

#-----------------------------------------------
# CTF 
#-----------------------------------------------
ctfHeader: Game On! 
ctfHeaderMessage: We are so excited to offer multiple Capture The Flag (CTF) competitions. Play one or play them all! All CTFs require a laptop and have both offensive and defensive challenges.
ctfHeaderMessageFloor: Visit the CTF on the 9th floor
# Really we don't want an odd number of CTFs. If we have odd, it'll look a little strange 
# on the desktop version
ctfs:
  #
  # CTFd 
  #
  - logo: ctfd.svg
    header: Play Whenever
    features:
      - Jeopardy-Style CTF
      - Reverse engineering, vulnerable web applications, and more
      - Play all day or casually pick up a challenge
      - Individual or team-based
      - Compare your progress against others on leaderboard
    registration: # No more than 2 registration buttons
      - url: https://ctfd.io
        disabled: true 
        title: Register Now
    registrationMessage: Registration opens day of event
    url: https://ctfd.io
  #
  # Pros Vs Joes
  #
  - logo: PvJlogo.png 
    header: Full Day Event
    features:
      - Register before BSidesNYC to participate
      - Offensive vs Defensive Style CTF
      - Team based activities
      - "\"Joes\" learn and face challenges"
      - "\"Pros\" flex their skills and help the Joes"
    registration: # No more than 2 registration buttons
      - url: https://forms.gle/68pwNwQARzPMuMjY7 
        disabled: false
        title: Pro Registration 
      - url: https://forms.gle/MaHcxPg9nZPDv98X9 
        disabled: false
        title: Joe Registration
    registrationMessage: 
    url: http://prosversusjoes.net/

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: ""
twitterHashTag: "bsidesnyc"
twitterFeed: ""

#-----------------------------------------------
# Sessionize Links
#-----------------------------------------------
sessionizeJsonSpeakerList: https://sessionize.com/api/v2/1kzdzu2h/view/Speakers
sessionizeJsonSessionList: https://sessionize.com/api/v2/1kzdzu2h/view/Sessions
sessionizeJsonAllData: https://sessionize.com/api/v2/1kzdzu2h/view/All
# Important: Select "Use UTC timezone for schedule" for the schedule grid in sessionize
sessionizeJsonScheduleGrid: https://sessionize.com/api/v2/1kzdzu2h/view/GridSmart

